import type { BlockEditProps } from '@wordpress/blocks';

export type SectionMedia = {
	id?: number | string;
	url?: string;
	alt?: string;
};

export type SectionAttributes = {
	align?: string;
	anchor?: string;
	skipLayout?: boolean;
	contentMaxWidthPreset?: string;
	contentMaxWidth?: number;
	minHeight?: string;
	gapSize?: string;
	resetMinHeightTablet?: boolean;
	resetMinHeightMobile?: boolean;
	verticalAlign?: string;
	verticalAlignTablet?: string;
	verticalAlignMobile?: string;
	horizontalAlign?: string;
	horizontalAlignTablet?: string;
	horizontalAlignMobile?: string;
	backgroundColor?: string;
	customBackgroundColor?: string;
	backgroundGradient?: string;
	backgroundGradientFirstColor?: string;
	backgroundGradientFirstColorLocation?: number;
	backgroundGradientSecondColor?: string;
	backgroundGradientSecondColorLocation?: number;
	backgroundGradientType?: string;
	backgroundGradientAngle?: number;
	foregroundGradient?: string;
	foregroundGradientFirstColor?: string;
	foregroundGradientFirstColorLocation?: number;
	foregroundGradientSecondColor?: string;
	foregroundGradientSecondColorLocation?: number;
	foregroundGradientType?: string;
	foregroundGradientAngle?: number;
	backgroundImage?: SectionMedia;
	backgroundCustomImagePosition?: { x: number; y: number };
	backgroundImagePosition?: string;
	backgroundImageAttachment?: string;
	backgroundImageRepeat?: string;
	backgroundImageSize?: string;
	sliderImages?: SectionMedia[];
	sliderAnimationEffect?: string;
	sliderAnimationDuration?: string;
	sliderAnimationSpeed?: string;
	backgroundVideoType?: string;
	youTubeVideoUrl?: string;
	youTubeVideoScale?: string;
	youTubeVideoMute?: string;
	youTubeVideoLoop?: string;
	youTubeVideoAutoplay?: string;
	backgroundVideoUrl?: SectionMedia;
	backgroundVideoMute?: boolean;
	backgroundVideoLoop?: boolean;
	backgroundVideoAutoplay?: boolean;
	backgroundVideoPoster?: string;
	backgroundVideoControlsPosition?: string;
	foregroundOpacity?: number;
	foregroundColor?: string;
	foregroundImage?: SectionMedia;
	foregroundCustomImagePosition?: { x: number; y: number };
	foregroundImagePosition?: string;
	foregroundImageAttachment?: string;
	foregroundImageRepeat?: string;
	foregroundImageSize?: string;
	foregroundFilter?: string;
	dividerTop?: string;
	dividersTopHeight?: string;
	dividerTopColor?: string;
	dividerBottom?: string;
	dividersBottomHeight?: string;
	dividersBringTop?: boolean;
	dividerBottomColor?: string;
	entranceAnimation?: string;
	entranceAnimationDuration?: string;
	entranceAnimationDelay?: string;
	paddingTopValue?: string;
	paddingBottomValue?: string;
	paddingLeftValue?: string;
	paddingRightValue?: string;
	paddingTop?: string;
	paddingBottom?: string;
	paddingLeft?: string;
	paddingRight?: string;
	paddingTopTablet?: string;
	paddingBottomTablet?: string;
	paddingLeftTablet?: string;
	paddingRightTablet?: string;
	paddingTopMobile?: string;
	paddingBottomMobile?: string;
	paddingLeftMobile?: string;
	paddingRightMobile?: string;
	marginTopValue?: string;
	marginBottomValue?: string;
	marginLeftValue?: string;
	marginRightValue?: string;
	marginTop?: string;
	marginBottom?: string;
	marginLeft?: string;
	marginRight?: string;
	marginTopTablet?: string;
	marginBottomTablet?: string;
	marginLeftTablet?: string;
	marginRightTablet?: string;
	marginTopMobile?: string;
	marginBottomMobile?: string;
	marginLeftMobile?: string;
	marginRightMobile?: string;
	className?: string;
};

export type SectionEditProps = BlockEditProps< SectionAttributes > & {
	className?: string;
};
